version: '3'

services:
  jekyll:
    container_name: online-cv
    image: jekyll/jekyll:4.0
    command: jekyll serve --watch --force_polling --verbose --livereload --host 192.168.0.21
    network_mode: host
    volumes:
      - .:/srv/jekyll
    ports:
      - 4001:4001
